<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <Nullable>enable</Nullable>
    <Features>$(Features);runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="GenHTTP.Core.Kestrel" Version="11.0.0" />
    <PackageReference Include="GenHTTP.Modules.Files" Version="11.0.0" />
    <PackageReference Include="GenHTTP.Modules.Webservices" Version="11.0.0" />
    <PackageReference Include="GenHTTP.Modules.Websockets" Version="11.0.0" />

    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />

    <PackageReference Include="Npgsql" Version="10.0.3" />

  </ItemGroup>

</Project>
